### ISSUE TITLE
[Question] applying dobin to univariate time series

### ISSUE THREAD

**Issue by leungi** [sevvandi/dobin#1]
Thanks for package.

For univariate time series, I used the timesteps of measured values as a dummy second dimension, and got mixed results, in terms of what I'd visually identify as outliers.

Is dobin applicable to univariate time series to start? If so, is using timesteps the correct approach?

**Comment by leungi** [comment]
Adjusting the cutoff value to the resulting components of `coords` from `dobin()` call helps, but it seems to be very case-dependent.

**Comment by sevvandi** [comment]
First, dobin is not meant for time series data in its raw form. But you can use dobin for a time series  by converting the time series to a set of features.  You can use the package  tsfeatures for this. Then, you can use dobin on these extracted features.  Hope this helps.

**Comment by leungi** [comment]
Noted; thanks for suggestion @sevvandi!

**Comment by leungi** [comment]
@sevvandi: tried your suggestion but outcome is not very satisfactory; reprex below.

Based on plot, I was hoping data point 4 and 20 would be flagged, but it seems `dobin()` output is unable to cluster properly.

Would love to hear your comments.

``` r
library(tsfeatures)
#> Warning: package 'tsfeatures' was built under R version 3.5.3
library(dobin)
#> Warning: package 'dobin' was built under R version 3.5.3
library(tidyverse)
#> Warning: package 'tidyverse' was built under R version 3.5.3
#> Warning: package 'ggplot2' was built under R version 3.5.3
#> Warning: package 'tidyr' was built under R version 3.5.3
#> Warning: package 'readr' was built under R version 3.5.2
#> Warning: package 'purrr' was built under R version 3.5.3
#> Warning: package 'stringr' was built under R version 3.5.3
#> Warning: package 'forcats' was built under R version 3.5.3

set.seed(1234)

my_data <- data.frame(
  x = 1:50,
  y = c(
    rep(30, 25) * abs(rnorm(25)),
    rep(30, 25) * -abs(rnorm(25))
  )
)

plot(my_data$x, my_data$y)
```

![](https://i.imgur.com/S77zLpT.png)

``` r

# create analysis to apply tsfeatures() on
window_len <- 6L

# apply tsfeatures() and apply dobin()
slide::slide(my_data$y, ~ (.x), .before = (window_len - 1L)) %>%
  keep(~ length(.x) >= window_len) %>%
  map_dfr(tsfeatures) %>%
  janitor::remove_empty("cols") %>%
  dobin() -> out

labs <- rep("norm", dim(out$coords)[1])
inds <- which(out$coords[, 1] > 0.5)

my_data %>%
  mutate(idx = row_number()) %>%
  mutate(outlier = if_else(idx %in% inds, 1, 0)) %>%
  ggplot(aes(x, y, colour = as.factor(outlier))) +
  geom_point()
```

![](https://i.imgur.com/RN3Yg07.png)

<sup>Created on 2019-11-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by sevvandi** [comment]
@leungi ,  I hope you find this post helpful. https://sevvandi.netlify.com/post/dobin-for-time-series/

**Comment by leungi** [comment]
I'm so touched you created this blog especially for this issue 😭; thanks!

The main difference between your blog and my example was that you _break a time series into consecutive non-overlapping windows and compute features of data in each window_, whereas I did overlapping.

I used the same data above and followed your steps (including using the `norm = 2` option in `dobin()` but still didn't get the expected outcome.

Speaking of which, `norm = 2` doesn't seem to be in `man` page.

```r
  library(tsfeatures)
  library(dobin)
  library(tidyverse)

  set.seed(1234)

  my_data <- data.frame(
    x = 1:50,
    y = c(
      rep(30, 25) * abs(rnorm(25)),
      rep(30, 25) * -abs(rnorm(25))
    )
  )

  plot(my_data$x, my_data$y)

  # create analysis to apply tsfeatures() on
  window_len <- 5L
  
  overlap <- FALSE

  # apply tsfeatures() and apply dobin()
  if (overlap) {
    slide::slide(my_data$y, ~ (.x), .before = (window_len - 1L)) %>%
      keep(~ length(.x) >= window_len) %>%
      map_dfr(tsfeatures) %>%
      select_if(~ !any(is.na(.))) %>% 
      dobin() -> out
  } else {
    data_split <- my_data %>% 
      split(rep(1:(nrow(my_data) / window_len), each = window_len))
    ftrs <- data_split %>%
      map_dfr(~tsfeatures(.x$y))
    ftrs %>%
      select_if(~ !any(is.na(.))) %>% 
      as.data.frame() %>% 
      janitor::remove_constant() %>% 
      dobin(norm = 2) -> out
  }
  
  coords <- as.data.frame(out$coords[ ,1:2])
  colnames(coords) <- c("DC1", "DC2")
  ggplot(coords, aes(DC1, DC2)) + geom_point() + theme_bw()
  
  # based on plots
  inds <- which(coords[ ,1] > 5 | coords[ ,1] < -2)

  # actual outcome
  inds
  #> [1] 2, 6

  # expected outcome - inds = 1, 4
```

**Comment by sevvandi** [comment]
@leungi, When you use overlapping windows, the original outlying observation in the time series  is in many windows giving rise to many points with high 'spikiness' (or what ever feature its outlying in ) in the feature space.  Because of this, in the feature space these points are not outliers anymore.  That's the reason for using non-overlapping windows.

**Comment by leungi** [comment]
Noted; make sense to not overlap.

However, the above example is still a mystery.

**Comment by sevvandi** [comment]
@leungi, did you find dobin useful for this work?
